// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYstgMfqa8_js6tlwLOxcWuEWjaJTvg7w',
    appId: '1:708043768140:web:8119df9e9e8c9c039f8fe9',
    messagingSenderId: '708043768140',
    projectId: 'listbook-58cec',
    authDomain: 'listbook-58cec.firebaseapp.com',
    storageBucket: 'listbook-58cec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__jeQcwX-fPJbWlpJnYgkvMPLfPvN08I',
    appId: '1:708043768140:android:0e34b93920be22c89f8fe9',
    messagingSenderId: '708043768140',
    projectId: 'listbook-58cec',
    storageBucket: 'listbook-58cec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVPnrZzPRBOIvzqZAvDWW0nEweE1CDf8',
    appId: '1:708043768140:ios:823373d741ea8b999f8fe9',
    messagingSenderId: '708043768140',
    projectId: 'listbook-58cec',
    storageBucket: 'listbook-58cec.appspot.com',
    iosBundleId: 'com.example.bookLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdVPnrZzPRBOIvzqZAvDWW0nEweE1CDf8',
    appId: '1:708043768140:ios:dea524d4fe195b2e9f8fe9',
    messagingSenderId: '708043768140',
    projectId: 'listbook-58cec',
    storageBucket: 'listbook-58cec.appspot.com',
    iosBundleId: 'com.example.bookLibrary.RunnerTests',
  );
}
